# Changes here will be overwritten by Copier
_commit: e730ed7
_src_path: gh:audivir/copier-template
author_email: pypi@audivir.de
author_name: Tim Hörmann
description: Python bindings for rattler-build.
github_org: audivir
project_name: rattler-bindings
project_slug: rattler_bindings
project_type: python
publishable: false
